server:
  port: 8082
spring:
  application:
    name: dubbo
  dubbo:
    server: true
    application:
      name: client
    registry:
      address: zookeeper://81.70.228.230:2181
    protocol:
      name: dubbo
    port: 20880
  scan: com.wxwk.client.server